### ISSUE TITLE
no display

### ISSUE THREAD

**Issue by jonwilliams-bluescape** [thp/eglo#1]
not sure what I've done, but it keeps telling me there's no display

**Comment by thp** [comment]
Do you have an X11 server running? Are you using Pocket CHIP or normal CHIP (with which output / firmware image / user interface)? Where/how are you trying to start the example, from xterm or via SSH? What is the value of the `$DISPLAY` variable?

**Comment by jonwilliams-bluescape** [comment]
I have a Pocket CHIP with X11 setup, ssh'd in with export DISPLAY=:0 so graphics go to the built-in display.
I had somehow completely destroyed my X11 while attempting to install the proper libraries, gave up, reinstalled, and when I checked this morning, everything "just works".
